### ISSUE TITLE
CPU usage spikes to 100%

### ISSUE THREAD

**Issue by ankitsharda** [bmc/daemonize#18]
I am using daemonize to covert binaries (of our own software) to daemons. I've experienced an issue where two of these binaries immediately show 100% of a core usage when they are started using daemonize. When I run them in tmux or in the foreground , they report normal CPU usage. Any ideas on what could be causing this ?

Ankit

**Comment by bmc** [comment]
Off the top of my head, no, not without more details. I've never seen this problem.

Note that there are significant differences between running under `tmux` or `screen` and running as a daemon. `tmux` and `screen` attach to a pseudo terminal, so the running process has a controlling terminal, doesn't ignore SIGHUP and the like, does not have to double-fork to disassociate from its controlling terminal, etc. Further, the process's parent is a shell—the shell spawned from `tmux`.

When running as a daemon, however:
* the process has no controlling terminal
* the process's parent is process ID 1 (due to the double forking)
* the process ignores SIGHUP, etc.

If your processes assume the existence of a terminal, they'll run fine under `tmux`, but they might not run fine under `daemonize`.

Regardless, I'm kind of flying blind here: I don't have enough information to even begin to help diagnose your problem.

**Comment by ankitsharda** [comment]
Thanks for the amazingly quick reply Brian. 
How do you suggest we go about debugging this ? For starters, I'm going to sit down with one of our developers tomorrow and attach to the above processes in gdb when they are run using daemonize. Any other pointers you think that we should look at ?

**Comment by bmc** [comment]
First, where are you running the code (Mac OS X, FreeBSD, Linux)? All three support a _daemon_(3) function that you can call directly from your code, instead of relying on an external tool like `daemonize`. That's a possible alternative.

Second, you can use the `-e` and `-o` options to `daemonize` to redirect `stderr` and `stdout`, respectively, to files, rather than `/dev/null`. Put some `printf` statements in your code, in addition to using `gdb`. (Attaching with a debugger will, of course, perturb the running of the program more dramatically than adding print statements will.)

**Comment by ankitsharda** [comment]
Thanks Brian. We will try this out at our end. 
We are using CentOS 6.6 minimal (Linux) x86_64 bit by the way. CentOS/Redhat do support the daemon function from /etc/init.d/functions . Does the daemonize program use this internally when available ? The man page for daemonize says so in the notes section :

NOTES :
If the host operating system provides the daemon(3) library routine, daemonize will use it. Otherwise, daemonize uses its own version of daemon(3).  This  choice  is  made  at  compile  time.  (BSD
 4.4-derived operating systems tend to provide their own daemon(3) routine.)

**Comment by bmc** [comment]
Yes, that's the case: If `daemonize` is compiled on a system that has _daemon_(3), it will use that call, instead of a local version.

However, daemonizing your program via an outside tool, vs. daemonizing it via calling _daemon_(3) directly, yourself, means you aren't in control of all aspects of the daemonizing. It might be easier to debug a program that uses _daemon_(3) directly. Of course, depending on the program, it might be more difficult.

I merely mention that approach as an alternative.

**Comment by ankitsharda** [comment]
This was an internal problem at our end. There was a problem with the process we were running with daemonize. Closing this thread

**Comment by bmc** [comment]
Okay, glad to hear it. Thanks for pre-emptively closing.
