### ISSUE TITLE
allow -o to specify a pipe to a [rotatelogs] command

### ISSUE THREAD

**Issue by dbabits** [bmc/daemonize#27]
@bmc My search lead me to the issue described in [Daemonize and logrotate](https://github.com/bmc/daemonize/issues/1)

I'm trying to roll my logs by using Apache's rotatelogs command. 
Like you mentioned, there are several others that are similar (e.g. tinylog, multilog, etc.)

I'm executing like this:
`myprogram 2>&1  | rotatelogs`

I think combining daemonize with log rotator would be very powerful and not a feature bloat.
Please note, that the venerable logrotate does not have the same functionality, here's a [good writeup why](http://jdebp.eu./FGA/do-not-use-logrotate.html)

Are there any other options that I might be missing?

Thanks,
D.

**Comment by bmc** [comment]
I completely agree with this statement in the referenced writeup: "The log rotation and the log writing must be done by the same code, so that it knows exactly when to do a rotation, does it exactly then, and does not race with a parallel process doing the other half of the task."

That's how it's been done for the last decade or so in the JVM community.

However, I still think it's wrong to put that logic inside `daemonize`. Here's why:

`daemonize` is just a wrapper that does some standard things, includng ensuring that standard  output,  error, and input are no longer connected to the terminal. I added some logic to redirect standard output and error to files, at the request of some users, but that's trivial logic.

Log rotation and log management is not trivial in the same sense. In addition, having `daemonize` handle the log rotation still violates the above precept: `daemonize` isn't doing the writing; it's simply closing or redirecting the file descriptors before invoking the actual program.

Finally, remember: If you use `daemonize` to make a daemon of program X, by the time program X actually starts running _`daemonize` is gone._ It sets things up, forks a couple times, and calls `exec(2)` to overlay itself with the real program.

It's not around any more to do the log management you want.

Log management is the responsibility of the programing doing the writing. It doesn't belong in a wrapper tool like `daemonize`.

**Comment by dbabits** [comment]
Brian,
thank you for your reply.
To clarify, I do not want daemonize to do log management at all.
I want rotatelogs program to do log management.
And daemonize to simply wire everything together as it does today, and exit.
Does it make sense?

**Comment by dbabits** [comment]
This is an [example](https://httpd.apache.org/docs/2.4/programs/rotatelogs.html) of how Apache webserver uses rotatelogs:
> CustomLog "|bin/rotatelogs /var/log/logfile 5M" common

So, evidently httpd process understands the | character and wires things up accordingly. 
I thought that daemonize could do something like this as well

**Comment by bmc** [comment]
So you want an additional option that says, "instead of closing stdout, pipe it here".

In effect, you want `daemonize` to then create _two_ daemons, one for your program and another for the log rotator program, and then pipe them together.

Okay, that's a legitimate desire, but why have `daemonize` reimplement a feature that's already available in the shell? Why not write a small shell script, like this?

```bash
#!/usr/bin/env bash
exec some_program | rotatelogs /var/log/logfile 5M some_program.log
```

Then, call daemonize like this:

```
daemonize -o /var/log/some_program.stdout -e /var/log/some_program.stderr /bin/bash /path/to/wrapper.sh
```

**Comment by bmc** [comment]
I am being resistant to your suggestion mostly because (a) the functionality you want exists elsewhere already, and (b) I tried to write (and maintain) `daemonize` using the traditional Unix philosophy of a small, composable tool that does one thing well. 

I don't want to add things to it that bleed past its original mission, which was "Make a daemon out of this thing for me."

**Comment by bmc** [comment]
Yeah, I had to be talked into `-e` and `-o`, as I recall. They were comparatively simple, though, so I finally gave in.
